# Meta
title:       Masatoshi Nishiguchi
tagline:     Web developer
description: >
  An aspiring web developer who specializes in HTML5, CSS3, Ruby, Rails and AngularJS
keywords:    >
  html, css, javascript, ruby, rails, angularjs, reactjs, web development

version:     1.0.0
github:
  repo:      https://github.com/mnishiguchi/mnishiguchi.github.io

# About/contact
author:
  name:              Masatoshi Nishiguchi
  url:               http://mnishiguchi.com
  email:             nishiguchi.masa@gmail.com
  github_url:        https://github.com/mnishiguchi
  linkedin_url:      https://linkedin.com/in/mnishiguchi
  twitter_url:       https://twitter.com/mnishiguchiDC
  stackoverflow_url: http://stackoverflow.com/users/3837223/mnishiguchi

# Url and Permalinks
permalink:  pretty
url:        "http://mnishiguchi.com"  # Hostname & protocol for your site
baseurl:    ""

# Navigation links in the header of the website
pages_list:
  Home:     '/'         # /index.html
  About:    '/about'    # /about.html
  Blog:     '/blog/'    # /blog/index.html
  Projects: '/projects' # /project.html
  # Archive:  '/archive'

# Pagination
paginate:      5
paginate_path: /blog/page:num

# Assets
sass:
  sass_dir: _sass  # Specify the directory that contains sass partials.
  style:    :compressed

# Include custom directories
include: ['_pages']

# Exclude from _site
exclude: ['node_modules']

# Post excerpts
excerpt_separator: <!--more-->

# Feed
feed: false

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  # - jekyll-redirect-from
# The jekyll-redirect-from gem allows URL Redirects: https://help.github.com/articles/redirects-on-github-pages
