# Permalinks
permalink:           pretty

# Setup
title:               Masatoshi Nishiguchi
tagline:             Web developer
url:                 https://mnishiguchi.github.io/blog
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Masatoshi Nishiguchi
  url:               https://twitter.com/mnishiguchiDC
  email:             nishiguchi.masa@gmail.com

# Custom vars
version:             0.0.1
github:
  repo:              https://github.com/mnishiguchi/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
