# Permalinks
permalink:           pretty

# Setup
title:               Masatoshi Nishiguchi
tagline:             Web developer
description:         Masatoshi Nishiguchi's blog
url:                 "http://mnishiguchi.com"  # the base hostname & protocol for your site
baseurl:             ""

# Navigation links in the header of the website
pages_list:
  Home:     '/'
  About:    '/about'
  Blog:     '/blog'
  Projects: '/projects'
  Archive:  '/archive'

# Pagination
paginate:            5
paginate_path:       /blog/page:num

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Include custom directories
include: ['_pages']

# Exclude from _site
exclude: ['node_modules']

# Post excerpts
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Masatoshi Nishiguchi
  url:               http://mnishiguchi.com
  email:             nishiguchi.masa@gmail.com
  github_url:        https://github.com/mnishiguchi
  linkedin_url:      https://linkedin.com/in/mnishiguchi
  twitter_url:       https://twitter.com/mnishiguchiDC
  stackoverflow_url: http://stackoverflow.com/users/3837223/mnishiguchi

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/mnishiguchi/mnishiguchi.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  # - jekyll-redirect-from
# The jekyll-redirect-from gem allows URL Redirects: https://help.github.com/articles/redirects-on-github-pages
